### ISSUE TITLE
Switch `master` branch to `main`

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive-versions#10]
- [x] Stop instance.
- [x] Update ops.
- [x] Rename `versions` folder on instance server to `versions-before-switching-to-main`.
- [x] Rename `master` into `main` through GitHub UI.

**Comment by martinratinaud** [comment]
PRs

- CORE https://github.com/ambanum/OpenTermsArchive/pull/862

**Comment by martinratinaud** [comment]
- Deployed 
- ssh on machine and verified that versions folder has been created
- versions git is on main branch as expected
