### ISSUE TITLE
This repository description has outdated link

### ISSUE THREAD

**Issue by Kissaki** [ambanum/OpenTermsArchive-versions#13]
This repos GitHub description is

> Documentation: https://github.com/OpenTermsArchive/contrib-versions#exploring-the-versions-history

The README.md has no such section to link to, and [never did](https://github.com/OpenTermsArchive/contrib-versions/commits/main/README.md).

The [ambanum/OpenTermsArchive repository README.md has that section though](https://github.com/ambanum/OpenTermsArchive/blob/main/README.md#exploring-the-versions-history), so the link seems to link the wrong repository.

https://github.com/ambanum/OpenTermsArchive/blob/main/README.md#exploring-the-versions-history

**Comment by MattiSG** [comment]
Thank you very much for this catch @Kissaki, I just updated the link 👍
