### ISSUE TITLE
Better diff viewer

### ISSUE THREAD

**Issue by LVerneyPEReN** [ambanum/OpenTermsArchive-versions#5]
Hi,

I'm opening this one to discuss about possible alternative diff viewer (to Github's built-in), to improve the quality of diffs.

In particular, Github seems to have troubles with diffs within a line. See for instance https://github.com/ambanum/CGUs-versions/commit/270a1389a8fab67723c7b5a9f61efacc7ceb3734?branch=270a1389a8fab67723c7b5a9f61efacc7ceb3734&diff=unified#diff-28600bbf50094536c29f48719962e1fdL124-R124 where the full line is shown as being modified, leaving it up to the reader to compute the actual diff.

![Screenshot_2020-09-14 Update App Store Review Guidelines · ambanum CGUs-versions 270a138](https://user-images.githubusercontent.com/58298410/93087269-9b593c80-f698-11ea-819d-e866acfc59e8.png)

On the other hand, a proper diff tool with word-diff capability (https://editor.mergely.com/?wl=1 here) is able to provide a much useful diff:

![Screenshot_2020-09-14 Mergely - Diff online, merge documents](https://user-images.githubusercontent.com/58298410/93087342-b1ff9380-f698-11ea-91d2-037117181b57.png)

So this issue is here to discuss about possible alternative tools and the most easy to deploy ones.

Best

**Comment by LVerneyPEReN** [comment]
Gitlab seems to be **slightly** (emphasis on slightly :/) better here:

![Screenshot_2020-09-14 Update test md (b0eae109) · Commits · Lucas Verney test](https://user-images.githubusercontent.com/58298410/93087820-613c6a80-f699-11ea-9367-b017e6f71647.png)

I've set up a mirror [there](https://gitlab.com/LucasVerneyDGE/CGUs-versions) for testing it. The diff linked above can be seen at https://gitlab.com/LucasVerneyDGE/CGUs-versions/-/commit/270a1389a8fab67723c7b5a9f61efacc7ceb3734?expanded=1.

**Comment by martinratinaud** [comment]
I think Github has improved a lot its diff viewer and thus I close this issue
